export const scheduleData: WeekData[] = [
  {
    week: 1,
    lectures: [
      {
        lec: 1,
        read: '21.1-22.1',
        exam: 1,
        hw: null,
        lab: null,
        labExam: null,
      },
      {
        lec: 2,
        read: '22.2-22.end',
        exam: 1,
        hw: null,
        lab: 'Electrostatics',
        labExam: null,
      },
      {
        lec: 3,
        read: '23.all',
        exam: 1,
        hw: null,
        lab: null,
        labExam: null,
      },
    ],
  },
  {
    week: 2,
    lectures: [
      {
        lec: 4,
        read: '24.all',
        exam: 2,
        hw: null,
        lab: null,
        labExam: 'Lab Quiz',
      },
      {
        lec: 5,
        read: '25.1-25.3',
        exam: 2,
        hw: null,
        lab: 'E vs. V Fields',
        labExam: null,
      },
      {
        lec: 6,
        read: '25.4-25.end',
        exam: 2,
        hw: null,
        lab: 'Capacitors',
        labExam: null,
      },
    ],
  },
  {
    week: 3,
    lectures: [
      {
        lec: 7,
        read: null,
        exam: 2,
        hw: null,
        lab: null,
        labExam: null,
      },
      {
        lec: 8,
        read: '26.1-26.4',
        exam: 2,
        hw: 1,
        lab: 'Resistivity',
        labExam: null,
      },
      {
        lec: 9,
        read: '26.5-27.3',
        exam: 2,
        hw: null,
        lab: null,
        labExam: null,
      },
    ],
  },
  {
    week: 4,
    lectures: [
      {
        lec: 10,
        read: '27.4-28.1',
        exam: 2,
        hw: null,
        lab: 'Circuits',
        labExam: null,
      },
      {
        lec: 11,
        read: '28.2-28.7',
        exam: 3,
        hw: null,
        lab: 'RC Circuit',
        labExam: null,
      },
      {
        lec: 12,
        read: '28.8-29.1',
        exam: 3,
        hw: null,
        lab: null,
        labExam: null,
      },
    ],
  },
  {
    week: 5,
    lectures: [
      {
        lec: 13,
        read: null,
        exam: 3,
        hw: null,
        lab: null,
        labExam: null,
      },
      {
        lec: 14,
        read: '29.2-30.1',
        exam: 3,
        hw: 2,
        lab: 'e/m',
        labExam: null,
      },
      {
        lec: 15,
        read: null,
        exam: 3,
        hw: null,
        lab: null,
        labExam: 'Lab Mid-Term',
      },
    ],
  },
  {
    week: 6,
    lectures: [
      {
        lec: 16,
        read: '30.2-30.7',
        exam: 3,
        hw: null,
        lab: 'Mag Fields',
        labExam: null,
      },
      {
        lec: 17,
        read: '30.8-30.end',
        exam: 3,
        hw: null,
        lab: 'RL Circuit',
        labExam: null,
      },
      {
        lec: 18,
        read: '31.all',
        exam: 4,
        hw: null,
        lab: null,
        labExam: null,
      },
    ],
  },
  {
    week: 7,
    lectures: [
      {
        lec: 19,
        read: '32.1-32.4',
        exam: 4,
        hw: null,
        lab: 'RLC Circuit',
        labExam: null,
      },
      {
        lec: 20,
        read: null,
        exam: 4,
        hw: null,
        lab: null,
        labExam: null,
      },
      {
        lec: 21,
        read: '32.5-33.1',
        exam: 4,
        hw: 3,
        lab: null,
        labExam: null,
      },
    ],
  },
  {
    week: 8,
    lectures: [
      {
        lec: 22,
        read: '33.2-33.end',
        exam: 4,
        hw: null,
        lab: null,
        labExam: null,
      },
      {
        lec: 23,
        read: '34.all',
        exam: 5,
        hw: null,
        lab: null,
        labExam: null,
      },
      {
        lec: 24,
        read: '35.1-35.3',
        exam: 5,
        hw: null,
        lab: null,
        labExam: null,
      },
    ],
  },
  {
    week: 9,
    lectures: [
      {
        lec: 25,
        read: null,
        exam: 5,
        hw: null,
        lab: null,
        labExam: null,
      },
      {
        lec: 26,
        read: '35.4-36.4',
        exam: 5,
        hw: 4,
        lab: null,
        labExam: null,
      },
      {
        lec: 27,
        read: '36.5-37.1',
        exam: 5,
        hw: null,
        lab: null,
        labExam: null,
      },
    ],
  },
  {
    week: 10,
    lectures: [
      {
        lec: 28,
        read: '37.2-37.end',
        exam: 5,
        hw: null,
        lab: null,
        labExam: null,
      },
      {
        lec: 29,
        read: null,
        exam: 5,
        hw: 5,
        lab: null,
        labExam: 'Lab Final',
      },
      {
        lec: 30,
        read: null,
        exam: 6,
        hw: null,
        lab: null,
        labExam: null,
      },
    ],
  },
]
